version: "1.0"
info:
  model: int-scaffold
packages:
- name: DEMOProject
  gitServerName: sdbit_github
  gitUrl: https://github.com/wm-sdbit
  gitUsername: wm-sdbit
  gitBranch: main
services:
- serviceName: project.demo.integrations:demoFlow
  packages:
  - name: DEMOProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1032
